### ISSUE TITLE
Add params to /eventdescription route⏳

### ISSUE THREAD

**Issue by saranonearth** [technobyte-nitkkr/WebsiteFrontend20#14]
https://github.com/technobyte-nitkkr/WebsiteFrontend20/blob/6deea8f4b1b77175f028867f83fcc8d5de53b6c6/src/App.jsx#L65-L71

We will be getting the category name and event name from URL params of router object. So the route should be formatted like **/eventdescription/:category/:event**

**Comment by dec0deit** [comment]
i am working on this
