### ISSUE TITLE
React router setup🚀

### ISSUE THREAD

**Issue by saranonearth** [technobyte-nitkkr/WebsiteFrontend20#3]
- Setup react router [(Docs)](https://www.npmjs.com/package/react-router-dom)
- Add routes in App.jx
- Create corresponding views file
Note: Let the file extensions be .jsx for all the views and components.

Views to be created
```
- About.jsx (/about)
- Contact.jsx (/contact)
- Queries.jsx (/query)
- Devs.jsx (/devs)
- Category.jsx (/categories)
- Events.jsx (/events)
- EventDescription.jsx (/eventdetails)
- Home.jsx (/home)

```

**Comment by dec0deit** [comment]
i will work on this.
